instrumentation:
    excludes: [lib/**/* indexAMD.js main/AMD-static-resolver.js parse/msgennyparser.js parse/mscgenparser.js parse/xuparser.js platoreports/**/* coverage/**/* render/graphics/templates/**]
    include-all-sources: true
