instrumentation:
    excludes: [lib/**/* indexAMD.js parse/msgennyparser_node.js parse/mscgenparser_node.js parse/xuparser_node.js doc/**/* platoreports/**/* coverage/**/* render/graphics/templates/**]
    include-all-sources: true
